### ISSUE TITLE
能请教下您是怎么学习opencv的吗

### ISSUE THREAD

**Issue by 156235yuan** [YLDarren/opencvHandleImg#1]
看到很多的优化，例如降噪、二值化等等。非常惊讶，好奇是怎么学习的，感觉opencv的资料太少了

**Comment by YLDarren** [comment]
不好意思这么晚才回复你，非常抱歉。我主要是根据一个大佬的博客【https://blog.csdn.net/ysc6688/article/category/2913009】他里面详细的讲述了处理图像的过程，让我知道每一步应该做什么，每一个步都有一个目标；比如这个星期的目标是二值化、下个星期的目标是降噪等。我根据这些目标一个个击破，大多的时候我是根据百度、google、看博客、自己写小demo，更多的时候自己是去写代码去尝试(因为资料很少，更多的时候跟着别人c的思路，用java来尝试实现)；比如别人c中用了某个函数，我就去搜索java中是否有同样的接口，或者看看api；总之，有了每一步的目标，目标会驱动着你前进！

**Comment by 156235yuan** [comment]
感谢您的回答
